### ISSUE TITLE
DSLR statt PI CAM

### ISSUE THREAD

**Issue by HenkoPenko** [ronbal/photobooth#11]
Hab da noch eine Frage:
Wäre es irgendwie möglich anstatt die Pi Cam ein DSLR Kamera zu nutzen ?
Was muss mann da alles scriptmässig ändern damit das überhaupt funktioniert ?

**Comment by supi4ever** [comment]
Das würde ich auch gerne wissen , hat da jemand schon was in der Richtung gemacht bei dem tollen Projekt?

**Comment by ronbal** [comment]
Das müsste komplett geändert werden. Man müsste dann gphoto2 nutzen
