### ISSUE TITLE
Error video system not initialized

### ISSUE THREAD

**Issue by BlueForrest** [ronbal/photobooth#3]
Hi, 

I have checked several photobooth video's & programs.
Yours seems to be the best i've seen, so I installed on the Pi.
After install & reboot, when I run program, i'm getting next error on line 191

Traceback (most recent call last):
  File "photobooth.py", line 191, in <module>
    for event in pygame.event.get():
pygame.error: video system not initialized

any idea how to fix that?
Camera is enabled and working fine - tested with default camera.py program

Note: i"m not using a touch screen, only regular PC monitor.

thanks
Johan

**Comment by ronbal** [comment]
which os?
